In [ ]:
import folium
import pandas as pd
from folium.plugins import MarkerCluster
from folium.plugins import MousePosition
from folium.features import DivIcon

In [ ]:
#Mark all launch sites on a map

In [ ]:
# Load the launch site data from a CSV file
launch_sites_df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv')

# Select the relevant columns for launch sites (Site Name, Latitude, Longitude)
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long', 'class']]

# Remove duplicate launch sites to get unique locations
launch_sites_df = launch_sites_df.groupby(['Launch Site'], as_index=False).first()

# Display the unique launch sites
display(launch_sites_df)

    Launch Site        Lat        Long  class
0   CCAFS LC-40  28.562302  -80.577356      0
1  CCAFS SLC-40  28.563197  -80.576820      1
2    KSC LC-39A  28.573255  -80.646895      1
3   VAFB SLC-4E  34.632834 -120.610745      0

In [ ]:
# Get the average latitude and longitude to center the map
avg_lat = launch_sites_df['Lat'].mean()
avg_long = launch_sites_df['Long'].mean()

# Create a base map centered around the average location
site_map = folium.Map(location=[avg_lat, avg_long], zoom_start=5)

# Add a tile layer to the map
folium.TileLayer('OpenStreetMap').add_to(site_map)

# Iterate through each launch site and add a marker
for index, site in launch_sites_df.iterrows():
    # Create a marker for the launch site
    marker = folium.Marker(
        location=[site['Lat'], site['Long']],  # Latitude and Longitude of the launch site
        popup=site['Launch Site'],  # Display the launch site name when the marker is clicked
        icon=folium.Icon(color='blue', icon='info-sign')  # Set the marker color and icon
    )
    # Add the marker to the map
    marker.add_to(site_map)

# Display the map
display(site_map)

In [ ]:
import requests
import io
import pandas as pd

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'

# Use requests to download the content from the URL
response = requests.get(URL)
response.raise_for_status() # Raise an exception for bad status codes

# Read the content into a pandas DataFrame
spacex_csv_file = io.BytesIO(response.content)
spacex_df = pd.read_csv(spacex_csv_file)

# Display the first few rows of the dataframe
display(spacex_df.head())

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356

In [ ]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

In [ ]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

In [ ]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

In [ ]:
# For each launch site, add a Circle object to the map
# Display the Launch Site name on the popup
# For each launch site, add a Marker object to the map
# Display the Launch Site name on the Marker's label

for index, site in launch_sites_df.iterrows():
    # Create a Circle object for each launch site
    circle = folium.Circle(
        [site['Lat'], site['Long']],
        radius=1000, # Specify a reasonable radius in meters
        color='#d35400',
        fill=True
    ).add_child(folium.Popup(site['Launch Site']))

    # Create a Marker object for each launch site
    marker = folium.map.Marker(
        [site['Lat'], site['Long']],
        # Create an icon as a text label
        icon=DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % site['Launch Site'],
        )
    )

    # Add the Circle and Marker to the map
    site_map.add_child(circle)
    site_map.add_child(marker)

# Display the map with the launch sites
display(site_map)

In [ ]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label

In [ ]:
# Create a MarkerCluster object
marker_cluster = MarkerCluster()

# Add the MarkerCluster to the map
site_map.add_child(marker_cluster)

# Iterate through the spacex_df DataFrame to add markers to the MarkerCluster
for index, record in spacex_df.iterrows():
    # Determine the marker color based on the 'class' column (0 for failure, 1 for success)
    marker_color = 'green' if record['class'] == 1 else 'red'

    # Create a marker with the launch site name and color-coded icon
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        popup=record['Launch Site'],
        icon=folium.Icon(color=marker_color, icon='info-sign')
    )

    # Add the marker to the MarkerCluster
    marker_cluster.add_child(marker)

# Display the map with the success/failure markers
display(site_map)

In [ ]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

In [ ]:
#create a markercluster object
marker_cluster = MarkerCluster()

In [ ]:
#create a new column in space_df dataframe called marker_color to store the marker colors based on the class value
spacex_df['marker_color'] = spacex_df['class'].apply(lambda x: 'green' if x == 1 else 'red')

In [ ]:
#for each launch result in space_df dataframe, add a folium.Marker to marker_cluster
for index, record in spacex_df.iterrows():
    #create a folium.Icon object with the marker_color attribute based on the class value
    icon = folium.Icon(color=record['marker_color'])

In [ ]:
site_map.add_child(marker_cluster)
for index, record in spacex_df.iterrows():
  marker_cluster.add_child(marker)

site_map

In [ ]:
# Define the coordinates of a coastline, city, and highway near the launch sites
coastline_coordinate = [28.563197, -80.56768]
city_coordinate = [28.6104, -80.8078] # Titusville, Florida
highway_coordinate = [28.573255, -80.6554] # Closest point on highway 1 to KSC LC-39A

In [ ]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

In [ ]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

Use the MousePosition tool on the map above to find the coordinates of a point on the closest coastline to a launch site. Replace the placeholder coordinates in the code below with the coordinates you obtain.

In [ ]:
# Replace these with the coordinates obtained from MousePosition on the map
coastline_point_lat = 28.563197
coastline_point_lon = -80.56768

# Choose a launch site from the launch_sites_df to calculate the distance to
# For example, using the first launch site (CCAFS LC-40)
launch_site_lat = launch_sites_df.loc[0, 'Lat']
launch_site_lon = launch_sites_df.loc[0, 'Long']
launch_site_name = launch_sites_df.loc[0, 'Launch Site']

# Calculate the distance
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_point_lat, coastline_point_lon)

print(f"Distance from {launch_site_name} to coastline: {distance_coastline:.2f} km")

# Optionally, add a line to the map showing the distance
points = [[launch_site_lat, launch_site_lon], [coastline_point_lat, coastline_point_lon]]
folium.PolyLine(points, color='blue', weight=2.5, opacity=0.5).add_to(site_map)

# Add a marker for the coastline point
folium.Marker(
    location=[coastline_point_lat, coastline_point_lon],
    popup=f'Coastline ({distance_coastline:.2f} km)',
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % f"{distance_coastline:.2f} km",
    )
).add_to(site_map)

display(site_map)

Distance from CCAFS LC-40 to coastline: 0.95 km

In [ ]:
# Calculate and visualize distances from all launch sites to coastline, city, and highway

proximity_points = {
    'Coastline': coastline_coordinate,
    'City': city_coordinate,
    'Highway': highway_coordinate
}

colors = {
    'Coastline': 'blue',
    'City': 'red',
    'Highway': 'purple'
}

for index, site in launch_sites_df.iterrows():
    launch_site_lat = site['Lat']
    launch_site_lon = site['Long']
    launch_site_name = site['Launch Site']

    for point_name, coords in proximity_points.items():
        point_lat, point_lon = coords
        distance = calculate_distance(launch_site_lat, launch_site_lon, point_lat, point_lon)

        print(f"Distance from {launch_site_name} to {point_name}: {distance:.2f} km")

        # Add a polyline connecting the launch site to the proximity point
        points = [[launch_site_lat, launch_site_lon], [point_lat, point_lon]]
        folium.PolyLine(points, color=colors[point_name], weight=2.5, opacity=0.5).add_to(site_map)

        # Add a marker with the distance on the proximity point
        folium.Marker(
            location=[point_lat, point_lon],
            popup=f'{point_name} ({distance:.2f} km)',
            icon=DivIcon(
                icon_size=(20,20),
                icon_anchor=(0,0),
                html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % f"{distance:.2f} km",
            )
        ).add_to(site_map)

# Display the updated map
display(site_map)

Distance from CCAFS LC-40 to Coastline: 0.95 km
Distance from CCAFS LC-40 to City: 23.13 km
Distance from CCAFS LC-40 to Highway: 7.72 km
Distance from CCAFS SLC-40 to Coastline: 0.89 km
Distance from CCAFS SLC-40 to City: 23.16 km
Distance from CCAFS SLC-40 to Highway: 7.76 km
Distance from KSC LC-39A to Coastline: 7.82 km
Distance from KSC LC-39A to City: 16.25 km
Distance from KSC LC-39A to Highway: 0.83 km
Distance from VAFB SLC-4E to Coastline: 3827.89 km
Distance from VAFB SLC-4E to City: 3804.08 km
Distance from VAFB SLC-4E to Highway: 3819.47 km